require("dashboard").setup({
  theme = "doom",
  config = {
    header = {
      "",
      "",
      "",
      "",
      "  ███╗   ██╗███████╗ ██████╗ ██╗   ██╗██╗███╗   ███╗  ",
      "  ████╗  ██║██╔════╝██╔═══██╗██║   ██║██║████╗ ████║  ",
      "  ██╔██╗ ██║█████╗  ██║   ██║██║   ██║██║██╔████╔██║  ",
      "  ██║╚██╗██║██╔══╝  ██║   ██║╚██╗ ██╔╝██║██║╚██╔╝██║  ",
      "  ██║ ╚████║███████╗╚██████╔╝ ╚████╔╝ ██║██║ ╚═╝ ██║  ",
      "  ╚═╝  ╚═══╝╚══════╝ ╚═════╝   ╚═══╝  ╚═╝╚═╝     ╚═╝  ",
      "",
      "",
      "",
    },
    center = {
      {
        icon = "  ",
        icon_hl = "DashboardIcon",
        desc = "Find File          ",
        desc_hl = "DashboardDesc",
        key = "p",
        key_hl = "DashboardKey",
        action = "Telescope find_files",
      },
      {
        icon = "  ",
        icon_hl = "DashboardIcon",
        desc = "Recent Files       ",
        desc_hl = "DashboardDesc",
        key = "r",
        key_hl = "DashboardKey",
        action = "Telescope oldfiles",
      },
      {
        icon = "  ",
        icon_hl = "DashboardIcon",
        desc = "Find Text          ",
        desc_hl = "DashboardDesc",
        key = "f",
        key_hl = "DashboardKey",
        action = "Telescope live_grep",
      },
      {
        icon = "  ",
        icon_hl = "DashboardIcon",
        desc = "New File           ",
        desc_hl = "DashboardDesc",
        key = "n",
        key_hl = "DashboardKey",
        action = "enew",
      },
      {
        icon = "  ",
        icon_hl = "DashboardIcon",
        desc = "Config             ",
        desc_hl = "DashboardDesc",
        key = "c",
        key_hl = "DashboardKey",
        action = "edit ~/.config/nvim/init.lua",
      },
      {
        icon = "  ",
        icon_hl = "DashboardIcon",
        desc = "Quit               ",
        desc_hl = "DashboardDesc",
        key = "q",
        key_hl = "DashboardKey",
        action = "quit",
      },
    },
    footer = {
      "",
      "",
      "  Neovim loaded " .. #vim.tbl_keys(package.loaded) .. " packages  ",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    },
  },
})

-- Highlight groups for a cleaner look
vim.api.nvim_set_hl(0, "DashboardHeader", { fg = "#f78c6c" })
vim.api.nvim_set_hl(0, "DashboardIcon",   { fg = "#82aaff" })
vim.api.nvim_set_hl(0, "DashboardDesc",   { fg = "#c3e88d" })
vim.api.nvim_set_hl(0, "DashboardKey",    { fg = "#f78c6c", bold = true })
